### ISSUE TITLE
Small typo in chapter 06 tutorial notes 

### ISSUE THREAD

**Issue by FluffyBubu** [AutomationPanda/awesome-web-testing-playwright#1]
Hi @AutomationPanda

File location: 
https://github.com/AutomationPanda/awesome-web-testing-playwright/blob/74c516dcb0d421f4681d145d8ed6b387b5af5ef4/tutorial/06-scaling-tests.md

Current method call (see below screenshot):
`await myBoardsPage.clickBoard(boardName);`

Expected method call (according to what I see in your test code):
`await myBoardsPage.openBoard(boardName);`

![chapter-06-typo](https://github.com/AutomationPanda/awesome-web-testing-playwright/assets/66629210/dda6dce6-4822-451a-a0ae-757bd23fa833)

Loving this tutorial! Thanks for all the effort.

**Comment by AutomationPanda** [comment]
Thanks! I'll fix it tonight.

**Comment by AutomationPanda** [comment]
Fixed.
